name: 04-Using Actions

on: push

jobs: 
    build:
        runs-on: ubuntu-latest

        #1. install dependencies of react application
        #
    
        steps:
            - name: Say Hello
              run: echo "Hello World"
    echo-goodbye:
        runs-on: ubuntu-latest
        steps:
            - name: Successful step
              run: |
                echo "I will succeed"
                exit 0   
            - name: Say Goodbye
              run: echo "Goodbye World"