name: 04-Using Actions

on: push

jobs: 
    build:
        runs-on: ubuntu-latest
steps:
  - name: check out code
  uses: actions/checkout@v4
  - name: printing folders
  run: ls
        #0. checkout the code from repo
        #1. install dependencies of react application
        #2. execute automated tests
    
 