name: 05-1-Filters Activity Types

on:
    pull_request:
        types: 
            - opened
            - synchronize
        branches:
            - main

jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - run: echo "This workflow runs when a pull request is opened, synchronized or reopened"