name: My first workflow

on: push

jobs: 
    first_job:
        runs-on: ubuntu-lates
        steps:
            - name: welcome message
              run: echo "My first job"

            - name: list files
              run: ls

            - name: read files
              run: cat readme.md